server:
  port: 8080

mpesa:
  daraja:
    consumer-key: JiQPZnHrn0TkftZAvWZrj2ibuFsuxCRfZxA8eUX0T6r9YTud
    consumer-secret: sp0Bao3jdWpd5Z3kAuAFKzOQxYTK8LuYRT3Igg8CbiA42OOvvAQiRLzry5YAnN40
    grant-type: client_credentials
    oauth-endpoint:  https://sandbox.safaricom.co.ke/oauth/v1/generate
    register-url-endpoint: https://sandbox.safaricom.co.ke/mpesa/b2c/v1/registerurl
    simulate-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/b3c/v1/simulate
    shortCode: 234553
    confirmationURL: https://example.com
    validationURL: https://example.com

    responseType: Completed
#    b2c-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/b2c/v3/paymentrequest
    b2c-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest

    b2c-result-url: https://mydomain.com/b2c/result
    b2c-queue-timeout-url: https://mydomain.com/b2c/queue
    b2c-initiator-name: testapi
    b2c-initiator-password: Safaricom999!*!
    transactionResultUrl: https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          client: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mpesa